AZURE_LOCATION: 'westus3'
RESOURCE_NAME_PREFIX: 'tylerd'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'repalce me in repo secrets'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'
